services:
  scraper:
    build: .
    env_file:
      - .env
    environment:
      OUTPUT_PATH: /output/bins.ics
      TARGET_URL: https://bnr-wrp.whitespacews.com/#! 
      HEADLESS: "1"
    volumes:
      - /var/www:/output
